[main]
file_path = "../private/default.xex"
out_directory_path = "../ppc"
switch_table_file_path = "jump_table.toml"

skip_lr = true
skip_msr = true
ctr_as_local = true
xer_as_local = true
reserved_as_local = true
cr_as_local = true
non_argument_as_local = true
non_volatile_as_local = true

restgprlr_14_address = 0x82CA9420
savegprlr_14_address = 0x82CA93D0
restfpr_14_address = 0x82CADCEC
savefpr_14_address = 0x82CADCA0
restvmx_14_address = 0x830069F8
savevmx_14_address = 0x83006760
restvmx_64_address = 0x83006A8C
savevmx_64_address = 0x830067F4

setjmp_address = 0x83006C90
longjmp_address = 0x82CAFA30

functions = [
     #{ address = 0x821320F0, size = 0x000000DC },
]

invalid_instructions = [
    { data = 0x00000000, size = 4 }, # Padding
]
